//! Cross-language configuration for Ash-Rust symbol mapping
//!
//! This module provides configuration schema and loading for mapping between
//! Ash language symbols and their corresponding Rust implementations.
//! The configuration supports both manual and auto-generated mappings
//! with confidence levels and source tracking.
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
/// Cross-language configuration schema
///
/// Defines mappings between Ash symbols and their Rust implementations,
/// including metadata for confidence levels and source tracking.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CrossLangConfig {
    /// Configuration schema version
    pub version: u32,

    /// Rust crates to scan for symbols
    pub rust_crates: Vec<RustCrate>,

    /// Ash file extensions to process
    pub ash_extensions: Vec<String>,

    /// Symbol mappings from Ash to Rust
    pub mappings: Vec<SymbolMapping>,
}

/// Rust crate configuration for symbol discovery
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RustCrate {
    /// Name of the Rust crate
    pub name: String,

    /// Modules within the crate to scan
    pub modules: Vec<String>,

    /// File patterns to exclude from scanning
    #[serde(default)]
    pub exclude: Vec<String>,
}

/// Mapping between an Ash symbol and its Rust implementation
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SymbolMapping {
    /// Ash symbol name
    pub ash_symbol: String,

    /// Ash symbol kind (type, function, etc.)
    pub ash_kind: String,

    /// Fully qualified Rust symbol name
    pub rust_symbol: String,

    /// Rust symbol kind (enum, trait, struct, etc.)
    pub rust_kind: String,

    /// Confidence level of this mapping
    pub confidence: ConfidenceLevel,

    /// Source of this mapping (manual, auto-generated, heuristic)
    #[serde(default)]
    pub source: MappingSource,
}

/// Confidence level for symbol mappings
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ConfidenceLevel {
    /// Manually verified, stable API
    High,

    /// Auto-generated but stable
    Medium,

    /// Heuristic, may change
    Low,
}

/// Source of symbol mapping
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum MappingSource {
    /// Manually defined mapping
    #[default]
    Manual,

    /// Auto-generated from source analysis
    AutoGenerated,

    /// Heuristic-based mapping
    Heuristic,
}

/// Error type for configuration loading
#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    /// I/O error during file operation
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    /// YAML parsing error
    #[error("YAML parsing error: {0}")]
    Yaml(#[from] serde_yaml::Error),

    /// Configuration validation error
    #[error("Configuration validation error: {0}")]
    Validation(String),

    /// Configuration file not found
    #[error("File not found: {0}")]
    FileNotFound(PathBuf),
}

/// Result type for configuration operations
pub type ConfigResult<T> = Result<T, ConfigError>;

impl CrossLangConfig {
    /// Load configuration from a YAML string
    ///
    /// # Errors
    /// Returns `ConfigError` if the YAML is invalid or fails validation
    pub fn from_yaml(yaml: &str) -> ConfigResult<Self> {
        let config: Self = serde_yaml::from_str(yaml)?;
        config.validate()?;
        Ok(config)
    }

    /// Load configuration from a file
    ///
    /// # Errors
    /// Returns `ConfigError` if the file cannot be read or parsed
    pub fn from_file(path: &Path) -> ConfigResult<Self> {
        if !path.exists() {
            return Err(ConfigError::FileNotFound(path.to_path_buf()));
        }

        let content = fs::read_to_string(path).map_err(ConfigError::Io)?;
        Self::from_yaml(&content)
    }

    /// Validate configuration consistency
    ///
    /// # Errors
    /// Returns `ConfigError` if the configuration is invalid
    fn validate(&self) -> ConfigResult<()> {
        // Validate version is supported
        if self.version != 1 {
            return Err(ConfigError::Validation(format!(
                "Unsupported configuration version: {}. Only version 1 is supported",
                self.version
            )));
        }

        // Validate rust crate names are not empty
        for crate_info in &self.rust_crates {
            if crate_info.name.is_empty() {
                return Err(ConfigError::Validation(
                    "Rust crate name cannot be empty".to_string(),
                ));
            }
        }

        // Validate symbol mappings have required fields
        for mapping in &self.mappings {
            if mapping.ash_symbol.is_empty() {
                return Err(ConfigError::Validation(
                    "Ash symbol name cannot be empty".to_string(),
                ));
            }
            if mapping.rust_symbol.is_empty() {
                return Err(ConfigError::Validation(
                    "Rust symbol name cannot be empty".to_string(),
                ));
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_load_valid_config_from_str() {
        let yaml = "version: 1\nrust_crates:\n  - name: \"ash-core\"\n    modules: [\"effect\", \"capability\"]\n    exclude: [\"tests/*\"]\nash_extensions:\n  - \".ash\"\nmappings:\n  - ash_symbol: \"Effect\"\n    ash_kind: \"type\"\n    rust_symbol: \"ash_core::effect::Effect\"\n    rust_kind: \"enum\"\n    confidence: \"high\"\n";

        let config = CrossLangConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.version, 1);
        assert_eq!(config.rust_crates.len(), 1);
        assert_eq!(config.ash_extensions, vec![".ash"]);
        assert_eq!(config.mappings.len(), 1);

        let mapping = &config.mappings[0];
        assert_eq!(mapping.ash_symbol, "Effect");
        assert_eq!(mapping.rust_symbol, "ash_core::effect::Effect");
        assert_eq!(mapping.confidence, ConfidenceLevel::High);
        assert_eq!(mapping.source, MappingSource::Manual);
    }

    #[test]
    fn test_reject_invalid_version() {
        let yaml = "version: 2\nrust_crates: []\nash_extensions: []\nmappings: []\n";

        let result = CrossLangConfig::from_yaml(yaml);
        assert!(result.is_err());

        let error = result.unwrap_err();
        assert!(
            error
                .to_string()
                .contains("Unsupported configuration version")
        );
    }

    #[test]
    fn test_reject_empty_crate_name() {
        let yaml = "version: 1\nrust_crates:\n  - name: \"\"\n    modules: []\nash_extensions: []\nmappings: []\n";

        let result = CrossLangConfig::from_yaml(yaml);
        assert!(result.is_err());

        let error = result.unwrap_err();
        let error_msg = error.to_string();
        assert!(
            error_msg.contains("Rust crate name cannot be empty")
                || error_msg.contains("Configuration validation error"),
            "Expected error message about empty crate name, got: {error_msg}"
        );
    }

    #[test]
    fn test_reject_empty_symbol_names() {
        let yaml = "version: 1\nrust_crates: []\nash_extensions: []\nmappings:\n  - ash_symbol: \"\"\n    ash_kind: \"type\"\n    rust_symbol: \"ash_core::effect::Effect\"\n    rust_kind: \"enum\"\n    confidence: \"high\"\n";

        let result = CrossLangConfig::from_yaml(yaml);
        assert!(result.is_err());

        let error = result.unwrap_err();
        assert!(
            error
                .to_string()
                .contains("Ash symbol name cannot be empty")
        );
    }

    #[test]
    fn test_config_roundtrip() {
        let original = CrossLangConfig {
            version: 1,
            rust_crates: vec![RustCrate {
                name: "ash-core".to_string(),
                modules: vec!["effect".to_string()],
                exclude: vec!["tests/*".to_string()],
            }],
            ash_extensions: vec![".ash".to_string()],
            mappings: vec![SymbolMapping {
                ash_symbol: "Effect".to_string(),
                ash_kind: "type".to_string(),
                rust_symbol: "ash_core::effect::Effect".to_string(),
                rust_kind: "enum".to_string(),
                confidence: ConfidenceLevel::High,
                source: MappingSource::Manual,
            }],
        };

        let yaml = serde_yaml::to_string(&original).unwrap();
        let deserialized = CrossLangConfig::from_yaml(&yaml).unwrap();

        assert_eq!(original, deserialized);
    }

    #[test]
    fn test_load_from_file() {
        let mut temp_file = NamedTempFile::new().unwrap();
        let yaml = "version: 1\nrust_crates: []\nash_extensions: []\nmappings: []\n";

        write!(temp_file, "{yaml}").unwrap();

        let config = CrossLangConfig::from_file(temp_file.path()).unwrap();
        assert_eq!(config.version, 1);
    }

    #[test]
    fn test_file_not_found_error() {
        let result = CrossLangConfig::from_file(Path::new("/nonexistent/path.yaml"));
        assert!(result.is_err());

        let error = result.unwrap_err();
        match error {
            ConfigError::FileNotFound(path) => {
                assert_eq!(path, Path::new("/nonexistent/path.yaml"));
            }
            _ => panic!("Expected FileNotFound error"),
        }
    }

    #[test]
    fn test_confidence_levels() {
        let yaml = "version: 1\nrust_crates: []\nash_extensions: []\nmappings:\n  - ash_symbol: \"Effect1\"\n    ash_kind: \"type\"\n    rust_symbol: \"ash_core::effect::Effect\"\n    rust_kind: \"enum\"\n    confidence: \"high\"\n  - ash_symbol: \"Effect2\"\n    ash_kind: \"type\"\n    rust_symbol: \"ash_core::effect::Effect\"\n    rust_kind: \"enum\"\n    confidence: \"medium\"\n  - ash_symbol: \"Effect3\"\n    ash_kind: \"type\"\n    rust_symbol: \"ash_core::effect::Effect\"\n    rust_kind: \"enum\"\n    confidence: \"low\"\n";

        let config = CrossLangConfig::from_yaml(yaml).unwrap();
        assert_eq!(config.mappings[0].confidence, ConfidenceLevel::High);
        assert_eq!(config.mappings[1].confidence, ConfidenceLevel::Medium);
        assert_eq!(config.mappings[2].confidence, ConfidenceLevel::Low);
    }
}
