-- Kleisli composition is a generic Monad-derived operation. The current Ash
-- surface does not yet expose arbitrary selected-interface method dispatch for
-- a lawful carrier-polymorphic helper here, so std::algebra intentionally does
-- not publish concrete Option/Result wrapper functions from this module.
