//! App template manifest validation for Phase 199.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Current app template manifest schema version.
pub const TEMPLATE_SCHEMA_VERSION: &str = "ash-template-v1";

/// App template manifest metadata.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TemplateManifest {
    /// Manifest schema version.
    pub schema_version: String,
    /// Stable template identity.
    pub id: String,
    /// Template version.
    pub version: String,
    /// Human-facing description.
    pub description: String,
    /// Explicit runtime/admission profiles required by this template.
    pub required_profiles: Vec<String>,
    /// Provider expectations scoped to required profiles.
    pub providers: Vec<TemplateProviderExpectation>,
    /// Resource expectations used by generated files.
    pub resources: Vec<String>,
    /// Evidence expectations produced or checked by generated files.
    pub evidence_expectations: Vec<String>,
    /// Template parameters.
    pub parameters: Vec<TemplateParameter>,
    /// Files generated by the template.
    pub files: Vec<TemplateFile>,
    /// Checks that must pass after generation.
    pub generated_checks: Vec<GeneratedCheck>,
}

/// Expected provider surface under a required profile.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TemplateProviderExpectation {
    /// Required profile name.
    pub profile: String,
    /// Provider name.
    pub provider: String,
    /// Expected provider operations.
    pub operations: Vec<String>,
}

/// One template parameter.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TemplateParameter {
    /// Parameter name.
    pub name: String,
    /// Whether callers must supply this parameter.
    pub required: bool,
    /// Optional default value.
    pub default: Option<String>,
}

/// One generated template file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TemplateFile {
    /// Relative output path.
    pub path: String,
    /// File content before parameter substitution.
    pub content: String,
}

/// One generated-project validation command.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedCheck {
    /// Command to run.
    pub command: String,
    /// File the command validates.
    pub file: String,
}

/// Template manifest validation error.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum TemplateManifestError {
    /// A required field was empty.
    #[error("template manifest field `{field}` must not be empty")]
    EmptyField { field: &'static str },
    /// Schema version is not current.
    #[error("template manifest schema_version `{found}` is unsupported; expected `{expected}`")]
    UnsupportedSchema {
        /// Found schema version.
        found: String,
        /// Required schema version.
        expected: &'static str,
    },
    /// Version string is not supported.
    #[error("template manifest version `{version}` must use major.minor.patch numeric form")]
    InvalidVersion {
        /// Invalid version.
        version: String,
    },
    /// Identifier contains unsupported characters.
    #[error(
        "template manifest id `{id}` must contain only lowercase ASCII letters, digits, '.', '_' or '-'"
    )]
    InvalidId {
        /// Invalid id.
        id: String,
    },
    /// A repeated name was found.
    #[error("template manifest contains duplicate {kind} `{name}`")]
    Duplicate {
        /// Entity kind.
        kind: &'static str,
        /// Duplicate name.
        name: String,
    },
    /// A provider references an undeclared profile.
    #[error("template provider `{provider}` references undeclared profile `{profile}`")]
    UndeclaredProfile {
        /// Provider name.
        provider: String,
        /// Profile name.
        profile: String,
    },
    /// A generated file path is unsafe.
    #[error("template file path `{path}` must be relative and must not contain parent traversal")]
    UnsafePath {
        /// Unsafe path.
        path: String,
    },
    /// A generated check references an unknown file.
    #[error("template generated check `{command}` references unknown file `{file}`")]
    UnknownCheckFile {
        /// Check command.
        command: String,
        /// Referenced file.
        file: String,
    },
    /// Template content uses unsupported syntax.
    #[error("template file `{path}` contains unsupported syntax: {pattern}")]
    UnsupportedSyntax {
        /// File path.
        path: String,
        /// Matched unsupported pattern.
        pattern: &'static str,
    },
}

/// Validate a template manifest.
///
/// # Errors
///
/// Returns an error when required metadata is missing, stale, unsafe, authority-ambiguous, or
/// contains template content that is not accepted for productive Phase 199 templates.
pub fn validate_template_manifest(
    manifest: &TemplateManifest,
) -> Result<(), TemplateManifestError> {
    validate_non_empty("schema_version", &manifest.schema_version)?;
    validate_non_empty("id", &manifest.id)?;
    validate_non_empty("version", &manifest.version)?;
    validate_non_empty("description", &manifest.description)?;

    if manifest.schema_version != TEMPLATE_SCHEMA_VERSION {
        return Err(TemplateManifestError::UnsupportedSchema {
            found: manifest.schema_version.clone(),
            expected: TEMPLATE_SCHEMA_VERSION,
        });
    }

    validate_id(&manifest.id)?;
    validate_version(&manifest.version)?;

    if manifest.required_profiles.is_empty() {
        return Err(TemplateManifestError::EmptyField {
            field: "required_profiles",
        });
    }
    if manifest.files.is_empty() {
        return Err(TemplateManifestError::EmptyField { field: "files" });
    }
    if manifest.generated_checks.is_empty() {
        return Err(TemplateManifestError::EmptyField {
            field: "generated_checks",
        });
    }

    let profiles = collect_unique("profile", &manifest.required_profiles)?;
    collect_unique("resource", &manifest.resources)?;
    collect_unique("evidence_expectation", &manifest.evidence_expectations)?;
    validate_parameters(&manifest.parameters)?;
    validate_providers(&manifest.providers, &profiles)?;
    let files = validate_files(&manifest.files)?;
    validate_checks(&manifest.generated_checks, &files)?;

    Ok(())
}

fn validate_non_empty(field: &'static str, value: &str) -> Result<(), TemplateManifestError> {
    if value.trim().is_empty() {
        Err(TemplateManifestError::EmptyField { field })
    } else {
        Ok(())
    }
}

fn validate_id(id: &str) -> Result<(), TemplateManifestError> {
    if id.bytes().all(|byte| {
        byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'.' | b'_' | b'-')
    }) {
        Ok(())
    } else {
        Err(TemplateManifestError::InvalidId { id: id.to_string() })
    }
}

fn validate_version(version: &str) -> Result<(), TemplateManifestError> {
    let parts = version.split('.').collect::<Vec<_>>();
    if parts.len() == 3
        && parts
            .iter()
            .all(|part| !part.is_empty() && part.bytes().all(|byte| byte.is_ascii_digit()))
    {
        Ok(())
    } else {
        Err(TemplateManifestError::InvalidVersion {
            version: version.to_string(),
        })
    }
}

fn collect_unique(
    kind: &'static str,
    values: &[String],
) -> Result<BTreeSet<String>, TemplateManifestError> {
    let mut out = BTreeSet::new();
    for value in values {
        validate_non_empty(kind, value)?;
        if !out.insert(value.clone()) {
            return Err(TemplateManifestError::Duplicate {
                kind,
                name: value.clone(),
            });
        }
    }
    Ok(out)
}

fn validate_parameters(parameters: &[TemplateParameter]) -> Result<(), TemplateManifestError> {
    let mut names = BTreeSet::new();
    for parameter in parameters {
        validate_non_empty("parameter.name", &parameter.name)?;
        if !names.insert(parameter.name.clone()) {
            return Err(TemplateManifestError::Duplicate {
                kind: "parameter",
                name: parameter.name.clone(),
            });
        }
        if parameter.required
            && parameter
                .default
                .as_deref()
                .is_some_and(|value| value.is_empty())
        {
            return Err(TemplateManifestError::EmptyField {
                field: "parameter.default",
            });
        }
    }
    Ok(())
}

fn validate_providers(
    providers: &[TemplateProviderExpectation],
    profiles: &BTreeSet<String>,
) -> Result<(), TemplateManifestError> {
    for provider in providers {
        validate_non_empty("provider.profile", &provider.profile)?;
        validate_non_empty("provider.provider", &provider.provider)?;
        if !profiles.contains(&provider.profile) {
            return Err(TemplateManifestError::UndeclaredProfile {
                provider: provider.provider.clone(),
                profile: provider.profile.clone(),
            });
        }
        if provider.operations.is_empty() {
            return Err(TemplateManifestError::EmptyField {
                field: "provider.operations",
            });
        }
        collect_unique("provider.operation", &provider.operations)?;
    }
    Ok(())
}

fn validate_files(files: &[TemplateFile]) -> Result<BTreeSet<String>, TemplateManifestError> {
    let mut paths = BTreeSet::new();
    for file in files {
        validate_non_empty("file.path", &file.path)?;
        validate_non_empty("file.content", &file.content)?;
        validate_relative_path(&file.path)?;
        validate_supported_syntax(file)?;
        if !paths.insert(file.path.clone()) {
            return Err(TemplateManifestError::Duplicate {
                kind: "file",
                name: file.path.clone(),
            });
        }
    }
    Ok(paths)
}

fn validate_relative_path(path: &str) -> Result<(), TemplateManifestError> {
    let has_parent = path.split('/').any(|part| part == "..");
    if path.starts_with('/') || path.starts_with('\\') || path.contains(':') || has_parent {
        Err(TemplateManifestError::UnsafePath {
            path: path.to_string(),
        })
    } else {
        Ok(())
    }
}

fn validate_supported_syntax(file: &TemplateFile) -> Result<(), TemplateManifestError> {
    for pattern in [
        "observe ... with",
        "act ... with",
        "Proc<",
        "Act<",
        "Workflow<",
        "legacy workflow",
        "ambient authority",
        "direct provider",
    ] {
        let matched = match pattern {
            "observe ... with" => {
                file.content.contains("observe ") && file.content.contains(" with ")
            }
            "act ... with" => file.content.contains("act ") && file.content.contains(" with "),
            other => file.content.contains(other),
        };
        if matched {
            return Err(TemplateManifestError::UnsupportedSyntax {
                path: file.path.clone(),
                pattern,
            });
        }
    }
    Ok(())
}

fn validate_checks(
    checks: &[GeneratedCheck],
    files: &BTreeSet<String>,
) -> Result<(), TemplateManifestError> {
    for check in checks {
        validate_non_empty("generated_check.command", &check.command)?;
        validate_non_empty("generated_check.file", &check.file)?;
        if !files.contains(&check.file) {
            return Err(TemplateManifestError::UnknownCheckFile {
                command: check.command.clone(),
                file: check.file.clone(),
            });
        }
    }
    Ok(())
}
